### ISSUE TITLE
Invoke help manually

### ISSUE THREAD

**Issue by mwedgwood-rmn** [willyg302/clip.py#7]
I'd like my top-level (main) command to do nothing, and if called simply output the help text. I didn't find that use case in the docs, and I couldn't intuitively tell from the source how to go about it.

**Comment by willyg302** [comment]
I had to do something similar for an app I'm working on, and ended up with something like this:

```python
import sys
import clip

app = clip.App()

@app.main()
def f():
	pass

@f.subcommand()
def x():
	print('Invoked x!')

try:
	app.run(sys.argv[1:] or '-h')  # If no arguments, pass in -h for help text
except clip.ClipExit:
	pass
```

Understandably this is not ideal, so I'll try to figure out a way to make it easier. Several ideas:

1. Pass the Command in to the decorated function if necessary, sort of like Click's [`@click.pass_context`](http://click.pocoo.org/3/commands/#nested-handling-and-contexts), so you can do e.g. `this.help()` from within `f()`.
2. Have a global `app.help()`. The issue here is that commands are still invoked before their subcommands, so calling this will always short-circuit the program.

Any thoughts/feedback is welcome.

**Comment by mwedgwood-rmn** [comment]
Your workaround isn't really that unattractive, IMHO. Anything else seems overly complicated.

**Comment by willyg302** [comment]
Found a better way. You can find the docs for it [here](http://clippy.readthedocs.org/en/latest/commands/#defaultnone).

Thanks!
