### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by clearclaw** [willyg302/clip.py#8]
It would be a nice to have a way to dump/list all the sub-commands as a tree.  My current use has ~50+ leafnodes, my users are getting lost and they'd like some sort of overview.

**Comment by willyg302** [comment]
Since this is a fairly uncommon use case, I'd like to have it disabled by default. My thoughts are perhaps a Command flag like so:

```python
@app.main(description='A very unhelpful shopping list CLI program', enable_tree=True)
```

When specified, it will shim an option like `-t, --tree` into the Command, so that you can do this:

```bash
$ python shopping.py --tree
shopping
    - add
    - view
```

Naturally you could set this up to print from any subcommand, but it would be up to you to do so. Let me know if this works for you and I'll get right on it!

**Comment by clearclaw** [comment]
That would be fine, especially if given some flexibility for the flag used.

**Comment by willyg302** [comment]
Now at 0.2.1 on PyPI, docs [here](http://clippy.readthedocs.org/en/latest/commands/#tree_viewnone). I figured the best flexibility was the ability to specify which flag you want to use.
