### ISSUE TITLE
Specifying stdout and stderr for multiple Apps

### ISSUE THREAD

**Issue by EpicDavi** [willyg302/clip.py#9]
Hello!

Due to the `ClipGlobals` class, the `stdout` and `sterr` can only be specified once for multiple `App`s in the same Python run.

By this, I mean that if you have multiple `App` objects (a different one for each embedded use, etc) the `stdout` and `stderr` are set to value specified by the last instantiated `App`.

For example, in this code:

```Python
first_app = clip.App(stdout=first_stream)

# Later on...
second_app = clip.App(stdout=second_stream)
```

If I were to `clip.echo()` in a command in `first_app`, it would write to `second_stream`.

It may take some significant refactoring to fix this due to the structure of the project. If too large to fix, any workarounds available?

**Comment by willyg302** [comment]
Hi, thanks for the feedback!

Yes, the original thought of this was that certain functions like `echo()` and `exit()` should be sort-of-singletons, accessible from anywhere with minimal effort. Otherwise, you would have to start passing around references to apps or commands and that could get painful.

One solution I see is to maintain a table of streams keyed by app. So:

```python
first_app = clip.App(name='app1', stdout=first_stream)
second_app = clip.App(name='app2', stdout=second_stream)

clip.echo('some message', app='app1')  # Writes to first_app's stream
clip.echo('broadcast')  # Writes to all registered streams...?
```

In the general case you'd have only one app registered and so `clip.echo()` would function as expected. Let me know what you think!

**Comment by willyg302** [comment]
Due to inactivity, I have decided to implement this as previously described. You can grab it in `0.3.0`, and docs can be found [here](http://clippy.readthedocs.org/en/latest/embedding/#bonus-multiple-apps).

Feel free to reopen if you have any additional comments/concerns/suggestions. Thanks!

**Comment by EpicDavi** [comment]
Ah, I forgot I opened this issue!

Yes, it looks like a great solution. I especially like the use of `[appname].echo()`.

On a side note, 639baa0 is really useful. I had a project that I had to strip the newlines when making a stream, but now I don't have to do that!
